spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: paulo
logging:
  config:
    classpath: log4j2.xml
user:
  name: paulo
  age: 18
  env: prd